/**
 * Regenerates the mechanical half of every Journal > Encounters entry from the
 * live data files, so the numbers in the journal cannot drift from the game.
 *
 * Run:  node tools/gen_encounter_journal.js
 *
 * Each entry file is split into two halves:
 *   - Everything OUTSIDE the <!-- GEN:START --> / <!-- GEN:END --> markers is
 *     hand-authored prose (the synopsis, how the NPCs interact, flavour). This
 *     script never touches it.
 *   - Everything INSIDE the markers is derived from data/combatScenarios.js,
 *     data/enemyTypes.js and data/skills.js and is rewritten wholesale.
 *
 * Adding a new encounter or roster is therefore additive: drop the scenario in
 * combatScenarios.js, add it to SCENARIO_DOCS / ADVERSARY_DOCS below, rerun the
 * script, then write the synopsis above the marker.
 *
 * Deliberately EXCLUDED (dev-facing balance dials, not player knowledge):
 *   damageMultiplierPct, buildupMultiplierPct, aiProfile, mpRegenPerTurn.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const MD_DIR = join(ROOT, 'data/journal/md');
const OUT_DIR = join(MD_DIR, 'encounters');
const INDEX = join(MD_DIR, 'index.json');

const { COMBAT_SCENARIOS } = await import('../data/combatScenarios.js');
const { ENEMY_TYPES } = await import('../data/enemyTypes.js');
const { SKILLS } = await import('../data/skills.js');
const { Items: ITEMS } = await import('../data/items.js');

/** 'zafaar_amulet_lacerate' -> "Zafaar Pendant of Lacerations" */
function itemName(id) {
  const it = ITEMS[id];
  if (!it) return id;
  const affix = it.fixedAffix && it.fixedAffix.key ? ' ' + it.fixedAffix.key : '';
  return (it.name || id) + affix;
}

const NL = String.fromCharCode(10);
const GEN_START = '<!-- GEN:START - regenerated by tools/gen_encounter_journal.js, do not hand-edit below -->';
const GEN_END = '<!-- GEN:END -->';

// Encounter entries to emit. `extraTiers` folds variant scenarios (Gorrek's
// Reckoning ladder) into the parent entry instead of spawning 5 near-identical
// pages. `slug`/`order` drive placement in the journal tree.
const SCENARIO_DOCS = [
  { id: 'training_encounter_1', slug: 'basic-training-i', order: 10 },
  { id: 'training_encounter_2', slug: 'basic-training-ii', order: 20 },
  { id: 'training_encounter_3', slug: 'the-animated-six', order: 30 },
  { id: 'training_encounter_4', slug: 'huntsman-and-beasts', order: 40 },
  { id: 'training_encounter_5', slug: 'elemental-duelists', order: 50 },
  {
    id: 'training_encounter_6', slug: 'gorrek', order: 60,
    extraTiers: [1, 2, 3, 4, 5].map(n => 'training_encounter_6_reckoning_' + n),
  },
];

// Individual adversary entries. Keyed by enemy type; one page each, reusable
// across any number of encounters that field them.
const ADVERSARY_DOCS = [
  { type: 'animated_fighter_dummy', slug: 'chad-the-unbreakable', order: 10 },
  { type: 'animated_rogue_dummy', slug: 'shifty-eyed-mo', order: 20 },
  { type: 'animated_healer_dummy', slug: 'stan-of-the-light', order: 30 },
  { type: 'animated_warlock_dummy', slug: 'gary-the-grim', order: 40 },
  { type: 'animated_ranger_dummy', slug: 'doug-longshot', order: 50 },
  { type: 'animated_wizard_dummy', slug: 'lenny-the-magnificent', order: 60 },
  { type: 'huntsman_commander', slug: 'cade', order: 70 },
  { type: 'beast_oskar', slug: 'oskar', order: 80 },
  { type: 'beast_kiro', slug: 'kiro', order: 90 },
  { type: 'fire_duelist', slug: 'ember', order: 100 },
  { type: 'ice_duelist', slug: 'rime', order: 110 },
  // title override: the encounter page is also called "Gorrek", and a
  // duplicate title makes [[Gorrek]] ambiguous for the wikilink resolver.
  { type: 'berserker_boss', slug: 'gorrek-adversary', order: 120, title: 'Gorrek, the Berserker' },
];

const RESIST_KEYS = ['PhysicalResist', 'ElementalResist', 'NecroticResist'];

function actionLabel(sk) {
  const a = sk.actionCost;
  if (Array.isArray(a)) return a.join(' or ');
  return a || 'major';
}

function clean(text) {
  return String(text).replace(/\|/g, '\\|').replace(/\s+/g, ' ').trim();
}

function skillRow(id) {
  const sk = SKILLS[id];
  if (!sk) return '| `' + id + '` | - | - | - | *(skill not found)* |';
  const cost = sk.mpCost ? sk.mpCost + ' MP' : '-';
  const cd = sk.cooldown ? String(sk.cooldown) : '-';
  const desc = clean(sk.description || '*(undocumented)*');
  return '| **' + (sk.name || id) + '** | ' + actionLabel(sk) + ' | ' + cost + ' | ' + cd + ' | ' + desc + ' |';
}

function skillTable(ids) {
  if (!ids || !ids.length) return '_No abilities defined._' + NL;
  const rows = ['| Ability | Action | Cost | CD | Effect |', '|---|---|---|---|---|'];
  ids.forEach(id => rows.push(skillRow(id)));
  return rows.join(NL) + NL;
}

/** Compact, player-facing stat line. Omits dev balance dials by design. */
function statLine(t) {
  const bits = ['**HP** ' + (t.maxHP != null ? t.maxHP : '?')];
  if (t.maxMP) bits.push('**MP** ' + t.maxMP);
  const db = t.derivedBonus || {};
  const res = RESIST_KEYS.filter(k => db[k]).map(k => k.replace('Resist', '') + ' ' + db[k] + '%');
  if (res.length) bits.push('**Resists** ' + res.join(' / '));
  if (db.Resilience) bits.push('**Resilience** ' + db.Resilience);
  if (db.Evasion) bits.push('**Evasion** ' + db.Evasion);
  if (t.baseStats) {
    bits.push('**Stats** ' + Object.keys(t.baseStats).map(k => k + ' ' + t.baseStats[k]).join(' / '));
  }
  return bits.join(' - ');
}

function rosterTable(sc) {
  const rows = ['| Combatant | Type | HP | Abilities |', '|---|---|---|---|'];
  (sc.enemies || []).forEach(e => {
    const t = ENEMY_TYPES[e.type] || {};
    const name = e.name || t.name || e.type;
    rows.push('| **' + name + '** | `' + e.type + '` | ' + (t.maxHP != null ? t.maxHP : '?') + ' | ' + ((t.skills || []).length) + ' |');
  });
  return rows.join(NL) + NL;
}

function encounterBody(doc) {
  const sc = COMBAT_SCENARIOS[doc.id];
  if (!sc) throw new Error('scenario missing: ' + doc.id);
  const out = [];
  out.push('## Roster' + NL);
  out.push(rosterTable(sc));
  out.push('');

  // De-duplicate: encounter 1 fields six identical dummies.
  const seen = new Set();
  (sc.enemies || []).forEach(e => {
    if (seen.has(e.type)) return;
    seen.add(e.type);
    const t = ENEMY_TYPES[e.type] || {};
    const count = (sc.enemies || []).filter(x => x.type === e.type).length;
    const label = count > 1
      ? (t.name || e.type) + ' (x' + count + ')'
      : (e.name || t.name || e.type);
    out.push('### ' + label + NL);
    out.push(statLine(t) + NL);
    out.push(skillTable(t.skills));
    out.push('');
  });

  if (doc.extraTiers && doc.extraTiers.length) {
    out.push('## Reckoning Ladder' + NL);
    out.push('Each tier unlocks by clearing the one before it. Toughness is the primary lever; the kit itself only grows at the marked tiers.' + NL);
    const rows = ['| Tier | HP | Resists (P / E / N) | Resilience | New at this tier |', '|---|---|---|---|---|'];
    let prevSkills = new Set(ENEMY_TYPES[COMBAT_SCENARIOS[doc.id].enemies[0].type].skills || []);
    doc.extraTiers.forEach(tierId => {
      const tsc = COMBAT_SCENARIOS[tierId];
      if (!tsc) return;
      const t = ENEMY_TYPES[tsc.enemies[0].type] || {};
      const db = t.derivedBonus || {};
      const notes = [];
      const added = (t.skills || []).filter(s => !prevSkills.has(s)).map(s => (SKILLS[s] && SKILLS[s].name) || s);
      if (added.length) notes.push('gains ' + added.join(', '));
      if (t.initiativeSlowAuraPct) notes.push('Initiative-slow aura (' + t.initiativeSlowAuraPct + '%)');
      const chest = (tsc.enemies[0].drops || []).find(d => d.equip === 'chest');
      if (chest && chest.rarity) notes.push(chest.rarity + ' armour');
      (tsc.enemies[0].drops || [])
        .filter(d => d.equip === 'amulet' || d.equip === 'ring')
        .forEach(j => notes.push('wears the ' + itemName(j.itemId)));
      rows.push('| ' + tsc.name.replace(/^.*—\s*/, '') + ' | ' + t.maxHP + ' | '
        + (db.PhysicalResist || 0) + ' / ' + (db.ElementalResist || 0) + ' / ' + (db.NecroticResist || 0)
        + ' | ' + (db.Resilience || 0) + ' | ' + (notes.join('; ') || '-') + ' |');
      prevSkills = new Set(t.skills || []);
    });
    out.push(rows.join(NL) + NL);
  }
  return out.join(NL);
}

function adversaryBody(doc) {
  const t = ENEMY_TYPES[doc.type];
  if (!t) throw new Error('enemy type missing: ' + doc.type);
  const appears = Object.keys(COMBAT_SCENARIOS).filter(k => {
    const enemies = COMBAT_SCENARIOS[k].enemies || [];
    return enemies.some(e => e.type === doc.type);
  }).map(k => COMBAT_SCENARIOS[k].name);

  const out = [];
  out.push('## Profile' + NL);
  out.push(statLine(t) + NL);
  if (appears.length) {
    out.push('**Appears in:** ' + appears.join(', ') + NL);
  }
  out.push('## Abilities' + NL);
  out.push(skillTable(t.skills));
  return out.join(NL);
}

function frontmatter(o) {
  return ['---',
    'id: encounters/' + o.slug,
    'title: "' + o.title + '"',
    'slug: "' + o.slug + '"',
    'category: "encounters"',
    'subtab: "' + o.subtab + '"',
    'order: ' + o.order,
    'tags: [' + (o.tags || []).map(t => '"' + t + '"').join(', ') + ']',
    'status: "approved"',
    'teaser: false',
    'requires: []',
    'sort: ' + o.order,
    'version: 1',
    'updatedAt: ' + new Date().toISOString().slice(0, 10),
    '---', ''].join(NL);
}

/** Writes a file, preserving anything above the GEN marker. */
function emit(relPath, fm, heading, prose, generated) {
  const full = join(OUT_DIR, relPath);
  mkdirSync(dirname(full), { recursive: true });
  let head;
  if (existsSync(full)) {
    const cur = readFileSync(full, 'utf8');
    const i = cur.indexOf(GEN_START);
    head = i >= 0 ? cur.slice(0, i) : cur + NL + NL;
  } else {
    head = fm + '# ' + heading + NL + NL + prose + NL + NL;
  }
  writeFileSync(full, head + GEN_START + NL + NL + generated + NL + GEN_END + NL, 'utf8');
  return 'encounters/' + relPath;
}

const written = [];

SCENARIO_DOCS.forEach(doc => {
  const sc = COMBAT_SCENARIOS[doc.id];
  written.push(emit(
    doc.slug + '.md',
    frontmatter({
      slug: doc.slug, title: sc.name, subtab: 'Training Pit', order: doc.order,
      tags: ['encounters', 'training', 'combat'],
    }),
    sc.name,
    '_' + (sc.description || '') + '_' + NL + NL + '> **Synopsis pending.**',
    encounterBody(doc)
  ));
});

ADVERSARY_DOCS.forEach(doc => {
  const t = ENEMY_TYPES[doc.type];
  if (!t) { console.warn('  skipped (no such type): ' + doc.type); return; }
  const display = doc.title || (function () {
    for (const k of Object.keys(COMBAT_SCENARIOS)) {
      const hit = (COMBAT_SCENARIOS[k].enemies || []).find(e => e.type === doc.type);
      if (hit && hit.name) return hit.name;
    }
    return doc.type;
  })();
  written.push(emit(
    'adversaries/' + doc.slug + '.md',
    frontmatter({
      slug: doc.slug, title: display, subtab: 'Adversaries', order: doc.order,
      tags: ['encounters', 'adversary', 'combat'],
    }),
    display,
    '> **Profile pending.**',
    adversaryBody(doc)
  ));
});

// --- index.json -------------------------------------------------------------
const idx = JSON.parse(readFileSync(INDEX, 'utf8'));
let added = 0;
written.forEach(rel => { if (!idx.includes(rel)) { idx.push(rel); added++; } });
writeFileSync(INDEX, JSON.stringify(idx, null, 2) + NL, 'utf8');

console.log('wrote ' + written.length + ' entries (' + added + ' new in index.json)');
written.forEach(w => console.log('   ' + w));
