/**
 * tools/gen_weakness_journal.js
 *
 * Regenerates the numbers in the Weakness Scaling journal entry from the live
 * weakness config, run through the REAL engine functions.
 *
 *   - Everything ABOVE the <!-- GEN:START --> marker is hand-written prose and
 *     is never touched. Explain how a family works there.
 *   - Everything INSIDE the markers is derived, and is overwritten each run.
 *
 * Why this exists: the entry was hand-maintained, and by 2026-09 almost every
 * number in it was wrong. Not a few stale values — the intensity FORMULA it
 * described had been replaced, most caps had moved (Cold's evasion penalty said
 * 60%, the engine allowed 90%), and one effect was described acting on the wrong
 * thing entirely (Singed was said to raise incoming fire DAMAGE; it raises
 * incoming fire BUILDUP). Even the config's own comments had drifted, so they
 * were no safer a source than the Journal. Generated numbers cannot drift.
 *
 * The numbers come from tools/weaknessModel.js, the SAME model that
 * tools/weakness_snapshot.js guards as a golden master. A Journal disagreeing
 * with the golden master would look verified while being wrong.
 *
 * Run after any change to the weakness config:
 *   node tools/gen_weakness_journal.js
 */
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const ENTRY = join(ROOT, 'data/journal/md/systems/weakness_scaling.md');

const M = await import('./weaknessModel.js');
const {
  WeaknessV3, WeaknessFamilies, WeaknessTierNames, WEAKNESS_T2,
  familyIntensityMult, weaknessDotTick, lightningJoltOdds,
  effectValue, capFor, meterAtCap, decayOf,
} = M;

const GEN_START = '<!-- GEN:START - regenerated by tools/gen_weakness_journal.js, do not hand-edit below -->';
const GEN_END = '<!-- GEN:END -->';

// The order the Journal has always presented families in.
const ORDER = ['lightning', 'cold', 'fire', 'disorient', 'lacerate', 'expose', 'disease', 'toxic', 'curse'];
const TITLE = (id) => id.charAt(0).toUpperCase() + id.slice(1);

// What each effect DOES, in player terms. Only prose lives here — every number
// is computed. Each label was checked against the engine call site, because
// three of the old Journal's descriptions named the wrong target.
//
//   fmt   'pct'  a fraction shown as a percentage
//         'pts'  a fraction SUBTRACTED from another percentage (percentage points)
//         'flat' a whole number
//         'mult' a multiplier
//   round how the engine rounds a flat value ('floor' | 'round'), and its minimum
const EFFECTS = {
  'cold.t1.initiativePenalty':    { label: 'Initiative reduced', fmt: 'pct' },
  'cold.t1.gaugeRegenPenalty':    { label: 'Initiative Gauge regeneration reduced', fmt: 'pct' },
  'cold.t2.dmgDealtPenalty':      { label: 'Outgoing damage reduced', fmt: 'pct' },
  'cold.t2.evasionPenalty':       { label: 'Evasion reduced', fmt: 'pct' },
  'cold.t2.gaugeStartDrainBase':  { label: 'Initiative Gauge drained at turn start', fmt: 'flat', round: 'floor' },

  'fire.t1.onActLoss':            { label: 'Fire buildup lost each time the target acts', fmt: 'flat', round: 'floor', min: 1 },
  'fire.t1.incomingFireBonus':    { label: 'Incoming Fire buildup increased', fmt: 'pct' },

  'disorient.t1.costMultiplier':  { label: 'Ability costs increased', fmt: 'pct' },
  'disorient.t2.startDrainMPBase':{ label: 'MP drained at turn start', fmt: 'flat', round: 'floor' },

  'lacerate.t1.onActBuildupFlat': { label: 'Lacerate added to itself each time the target acts', fmt: 'flat', round: 'round', min: 1 },

  'expose.t1.physDRPen':          { label: 'Physical damage reduction lowered', fmt: 'pts' },
  'expose.t1.physBuildupAmp':     { label: 'Incoming Disorient and Lacerate buildup increased', fmt: 'pct' },
  'expose.t2.critChanceBonus':    { label: 'Attacker crit chance increased', fmt: 'pct' },
  'expose.t2.critDamageBonus':    { label: 'Attacker crit damage increased', fmt: 'pct' },

  'disease.t1.healRecvPenalty':   { label: 'Healing received reduced', fmt: 'pct' },
  'disease.t2.maxHPDown':         { label: 'Maximum HP reduced', fmt: 'pct' },

  'toxic.t1.decayBypassChance':   { label: 'Chance each turn that Toxic does not decay', fmt: 'pct' },

  'curse.t1.decayReduction':      { label: "Curse's own decay reduced", fmt: 'pct' },
  'curse.t2.decayReduction':      { label: "Curse's own decay reduced", fmt: 'pct' },
  'curse.t2.curseAmpMult':        { label: 'Amplification for curse-scaled on-hit effects', fmt: 'mult' },
};

// Effects deliberately presented in their own table rather than a family's.
// Listed so the completeness check below can tell "shown elsewhere" apart from
// "forgotten".
const SHOWN_ELSEWHERE = new Set([
  'lightning.t1.joltDieMax', 'lightning.t2.multiJoltChance', 'lightning.t2.extraJoltsMax',
  'lightning.t2.multiJoltChanceExp', 'lightning.t2.extraJoltsExp',
  'fire.t2.startTickBase', 'fire.t2.startTickCurveK', 'fire.t2.startTickCurveExp',
  'toxic.t2.startTickBase', 'toxic.t2.startTickCurveK', 'toxic.t2.startTickCurveExp',
  'lacerate.t2.startPctHP',
]);

// ---- completeness: refuse to write a Journal with an effect missing --------
//
// A new effect added to the config must not silently vanish from the Journal.
// This is the documentation form of the bug class this project keeps hitting:
// a field declared in data that nothing downstream accounts for.
{
  const unaccounted = [];
  for (const [fam, cfg] of Object.entries(WeaknessV3.families)) {
    for (const tier of ['t1', 't2']) {
      for (const [k, v] of Object.entries(cfg[tier] || {})) {
        if (typeof v !== 'number' || /Cap$/.test(k)) continue;
        const key = `${fam}.${tier}.${k}`;
        if (!EFFECTS[key] && !SHOWN_ELSEWHERE.has(key)) unaccounted.push(key);
      }
    }
  }
  if (unaccounted.length) {
    console.error('Refusing to generate: these weakness effects are in the config but not in the Journal:');
    unaccounted.forEach(k => console.error('  ' + k));
    console.error('Add a label to EFFECTS, or list the key in SHOWN_ELSEWHERE.');
    process.exit(1);
  }
}

// ---- formatting --------------------------------------------------------------

const num = (v, dp = 2) => (Math.round(v * 10 ** dp) / 10 ** dp).toString();

function fmtValue(meta, v) {
  if (v == null) return '—';
  switch (meta.fmt) {
    case 'pct': return `${Math.round(v * 100)}%`;
    case 'pts': return `${Math.round(v * 100)} pts`;   // non-breaking, so it stays on one line in a narrow cell
    case 'mult': return `×${num(v)}`;
    default: {
      let n = meta.round === 'round' ? Math.round(v) : Math.floor(v);
      if (meta.min != null) n = Math.max(meta.min, n);
      return String(n);
    }
  }
}

const row = (cells) => `| ${cells.join(' | ')} |`;
const header = (cells) => row(cells) + '\n' + row(cells.map(() => '---'));

// ---- sections --------------------------------------------------------------

const EFFECT_METERS = [200, 400, 800, 1600];

// Families whose Tier 2 effect is a damage tick. The tick lives in the Damage
// over time table, so without a pointer a reader of the family's own section
// sees only its Tier 1 row and could reasonably conclude Tier 2 does nothing.
const TICK_NOTE = {
  fire: 'Ablaze deals burn damage at the end of each turn; see **Damage over time** above.',
  toxic: 'Envenomed deals poison damage at the end of each turn; see **Damage over time** above.',
  lacerate: 'Hemorrhaging deals bleed damage at the end of each turn; see **Damage over time** above.',
};

function intensitySection() {
  const meters = [300, 400, 600, 800, 1200, 2400];
  const lines = [
    '## Intensity by family',
    '',
    'Intensity is **1.0 at 200** buildup in every family, and grows from there with no ceiling. Each effect below carries its own cap instead.',
    '',
    header(['Family', 'Curve', ...meters.map(m => `At ${m}`)]),
  ];
  for (const id of ORDER) {
    const c = WeaknessV3.families[id]?.intensity || {};
    const curve = c.formula === 'pow' ? `S ${c.S}, exp ${c.exp}` : (c.formula || 'global');
    lines.push(row([`**${TITLE(id)}**`, curve, ...meters.map(m => num(familyIntensityMult(id, m)))]));
  }
  return lines.join('\n');
}

function decaySection() {
  const meters = [50, 150, 200, 300, 400, 600, 800];
  const lines = [
    '## Decay per turn',
    '',
    'Buildup that is not refreshed is lost at the end of each turn. These are the amounts lost at each meter.',
    '',
    header(['Family', ...meters.map(m => `At ${m}`), 'Most per turn']),
  ];
  for (const id of ORDER) {
    const most = decayOf(id, 100000);
    lines.push(row([`**${TITLE(id)}**`, ...meters.map(m => String(decayOf(id, m))), String(most)]));
  }
  return lines.join('\n');
}

function familySection(id) {
  const names = WeaknessTierNames[id] || ['T1', 'T2'];
  const lines = [`### ${TITLE(id)} — *${names[0]} / ${names[1]}*`, ''];

  const rows = Object.keys(EFFECTS).filter(k => k.startsWith(id + '.'));
  if (!rows.length) return null;

  lines.push(header(['Tier', 'Effect', ...EFFECT_METERS.map(m => `At ${m}`), 'Cap', 'Cap reached']));
  for (const key of rows) {
    const [, tier, k] = key.split('.');
    const meta = EFFECTS[key];
    const cap = capFor(id, tier, k);
    const reached = meterAtCap(id, tier, k);
    lines.push(row([
      tier === 't1' ? names[0] : names[1],
      meta.label,
      ...EFFECT_METERS.map(m => fmtValue(meta, effectValue(id, tier, k, m))),
      cap == null ? 'none' : fmtValue(meta, cap),
      reached == null ? (cap == null ? '—' : 'beyond 5000') : `meter ${reached}`,
    ]));
  }
  if (TICK_NOTE[id]) lines.push('', TICK_NOTE[id]);
  return lines.join('\n');
}

function lightningSection() {
  const die = WeaknessV3.families.lightning?.t1?.joltDieMax ?? 4;
  const meters = [200, 300, 400, 600, 800, 1200, 1600, 2400];
  const lines = [
    '### Lightning — *Zapped / Shocked*',
    '',
    `**Zapped:** each jolt deals **1–${die}** damage. A jolt is added after every other part of the hit, so it is never scaled by skill bonuses, buffs or critical hits.`,
    '',
    '**Shocked:** each hit rolls some number of extra jolts, each landing independently. A hit always deals its first jolt, plus however many of the extra rolls land.',
    '',
    header(['Meter', 'Extra jolt rolls', 'Chance each lands', 'Average jolts per hit']),
  ];
  for (const m of meters) {
    const { rolls, chance } = lightningJoltOdds(m);
    lines.push(row([String(m), String(rolls), `${Math.round(chance * 100)}%`, (1 + rolls * chance).toFixed(1)]));
  }
  return lines.join('\n');
}

function dotSection() {
  const meters = [200, 300, 400, 600, 800, 1000, 1200, 1600, 2400];
  const lacCap = capFor('lacerate', 't2', 'startPctHP');
  const lines = [
    '## Damage over time',
    '',
    'Damage each family deals at the end of the target\'s turn, before resistances. Fire and Toxic deal a fixed amount set by the meter. Lacerate deals a share of the target\'s maximum HP.',
    '',
    header(['Meter', 'Fire (elemental)', 'Toxic (necrotic)', 'Lacerate (physical)']),
  ];
  for (const m of meters) {
    const fire = Math.max(1, Math.floor(weaknessDotTick('fire', m)));
    const toxic = Math.max(1, Math.floor(weaknessDotTick('toxic', m)));
    const lac = effectValue('lacerate', 't2', 'startPctHP', m);
    const atCap = lacCap != null && lac >= lacCap;
    lines.push(row([String(m), String(fire), String(toxic),
      `${Math.round(lac * 100)}% max HP${atCap ? ' *(cap)*' : ''}`]));
  }
  return lines.join('\n');
}

// ---- assemble --------------------------------------------------------------

function generate() {
  const parts = [
    intensitySection(),
    decaySection(),
    dotSection(),
    ['## Every effect, by family', '',
      'Values at four meters, the cap each effect stops at, and the meter where it first gets there.'].join('\n'),
    lightningSection(),
  ];
  for (const id of ORDER) {
    if (id === 'lightning') continue;
    const s = familySection(id);
    if (s) parts.push(s);
  }
  return parts.join('\n\n');
}

/** The whole file as it SHOULD be: the existing hand-written head, then a fresh block. */
function expected() {
  if (!existsSync(ENTRY)) throw new Error('journal entry not found: ' + ENTRY);
  const cur = readFileSync(ENTRY, 'utf8');
  const NL = cur.includes('\r\n') ? '\r\n' : '\n';
  const i = cur.indexOf(GEN_START);
  if (i === -1) {
    throw new Error('no GEN:START marker in ' + ENTRY + ' — add one below the hand-written prose first');
  }
  const head = cur.slice(0, i);
  const body = generate().replace(/\n/g, NL);
  return { cur, next: head + GEN_START + NL + NL + body + NL + NL + GEN_END + NL };
}

const rel = ENTRY.replace(ROOT + '\\', '').replace(ROOT + '/', '');

if (process.argv.includes('--print')) {
  // Shows the generated block without touching the entry, for review.
  console.log(generate());
} else if (process.argv.includes('--check')) {
  // The drift guard, run by `npm run verify`.
  //
  // Generating numbers only prevents staleness if someone regenerates. A balance
  // pass on the weakness config that forgets this step would quietly re-stale the
  // Journal — the exact state this file was written to end. So verify fails until
  // the entry matches the config again. The fix is always one command.
  const { cur, next } = expected();
  if (cur === next) {
    console.log('weakness journal is current');
  } else {
    console.error(`${rel} is out of date with the weakness config.`);
    console.error('Run:  node tools/gen_weakness_journal.js');
    process.exit(1);
  }
} else {
  const { next } = expected();
  writeFileSync(ENTRY, next, 'utf8');
  console.log('wrote ' + rel);
}
