/**
 * One-shot seeder for the hand-authored half of the Encounters journal entries.
 *
 * tools/gen_encounter_journal.js owns everything BELOW the GEN:START marker and
 * preserves everything above it. This script writes that "above" half once, so
 * the entries ship with real prose instead of "Synopsis pending". After this
 * runs, edit the .md files directly — rerunning the generator will not clobber
 * your prose, and rerunning THIS script will (it overwrites the head section).
 *
 * Run:  node tools/seed_encounter_prose.js
 */
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = join(ROOT, 'data/journal/md/encounters');
const GEN_START = '<!-- GEN:START - regenerated by tools/gen_encounter_journal.js, do not hand-edit below -->';
const NL = String.fromCharCode(10);

const PROSE = {
  'basic-training-i.md': `_Six stationary dummies for safe sparring._

The pit's first rack. Six straw-and-lacquer figures on fixed posts, weighted so they rock when struck and settle upright again. They do not move, do not target, and cannot deal damage — the only ability any of them has is a sway that exists so the turn order has something to advance past.

## How the fight works

There is no fight. Every dummy has 10 HP and no offence whatsoever, so the encounter runs entirely at your pace. It exists to let you confirm three things without any clock on you:

- **Targeting** — that you can select a specific figure in a specific slot, including ones behind others.
- **Reach** — which of your abilities can touch the back rank from where you are standing, and which cannot.
- **Resolution flow** — the shape of a turn: major action, bonus action, class action, and what each one consumes.

Six bodies across the field is deliberate. It is enough to make rank and column matter visually before anything is at stake.

## What it teaches

Positioning is not cosmetic. Which slot you occupy determines what you can reach and what can reach you, and this is the only encounter in the pit where you can learn that with no consequence for getting it wrong.

Move on to [[Basic Training II]] once targeting feels automatic.`,

  'basic-training-ii.md': `_Six reinforced dummies that shuffle around — practice range and AOE shapes._

The same rack, rebuilt on rollers. These are sturdier — twice the hit points — and, critically, they **move**. Each carries a shuffle that shifts it one column sideways, and they will use it to slide out of ground hazards they are standing in.

## How the fight works

Still no incoming damage. What changes is that the board no longer holds still for you.

- **Shapes have to be aimed at where a target will be**, not where it is. An area effect placed on a dummy's current square is a wasted action if it shuffles out before resolution.
- **Ground hazards get actively dodged.** The dummies treat hazard squares as something to leave, which is the first time the pit pushes back on a "drop a zone and forget it" habit.
- **Column matters.** A sideways shuffle changes which of your ranks can reach a given dummy, so a target that was in range at the top of the round may not be by the time your turn comes around.

## What it teaches

This is the AOE-shape trainer. Every custom shape in the game is described relative to ally and enemy slot numbers, and this encounter is where you learn to read those shapes on a board that is actually changing. Practise the ones you intend to rely on here, where a miss costs nothing.

After this, the pit stops being polite — [[The Animated Six]] hit back.`,

  'the-animated-six.md': `_Six animated constructs, real combat AI._

The first genuine fight in the pit, and a deliberate jump. Six constructs animated into distinct class roles, each running the same decision-making a real combatant would: they pick targets by threat and opportunity, hold abilities for the right moment, and — the part that catches people — **they respond to each other.**

## How the fight works

Treat this as six interlocking problems rather than six health bars.

- **[[Chad the Unbreakable]]** is the wall, and he does not merely soak damage — he can **redirect a blow onto himself** before your roll resolves. An attack aimed carefully at a fragile target in the back can simply land on Chad instead, at his defences rather than theirs.
- **[[Stan, of the Light]]** channels real healing across the party and cleanses weakness meters off his allies. He prioritises the lowest-health wounded ally and will not waste a cast on someone already at full, so chip damage spread across the group is close to worthless — he will simply top it back up.
- **[[Gary the Grim]]** and **[[Lenny the Magnificent]]** are the casters, and they fight with layered tactics rather than repeating one spell. Lenny channels a large area effect that must be answered; Gary works in curses and necrotic damage.
- **[[Doug Longshot]]** and **[[Shifty-Eyed Mo]]** are reactive. Both answer the moment an ally is struck. Mo's answer is the dangerous one: a curse that lands **before your attack rolls**, weakening the strike that triggered it rather than the next one.

The through-line is that damage alone does not close this fight. Stan undoes spread damage, Chad absorbs precision, and Mo taxes aggression. You have to break the support structure or commit hard enough to outpace it.

## What it teaches

Focus fire, and the order you break a formation in. This is the encounter where "kill the healer" stops being a cliché and becomes arithmetic — and where you learn that the tank's job is to make that plan not work.

## Damage typing

Weighted toward physical, with genuine necrotic pressure from Gary's curse kit. If you are testing resistances, this is a reasonable place to feel the difference between Physical and Necrotic mitigation.`,

  'huntsman-and-beasts.md': `_A huntsman commander leads two beasts._

Three combatants, and the first encounter built around a **commander**. [[Cade]] is not the damage — he is the reason the damage lands. Kill order is the entire puzzle.

## How the fight works

- **Cade marks and directs.** His mark applies Expose buildup and flags a target for focus, making his beasts far more likely to converge on whoever he has painted. He also hands out Initiative and Accuracy to the pack, and his stronger pack-wide buff only unlocks once a target is already carrying **two or more** active weaknesses — so the fight escalates as your meters fill.
- **[[Oskar]]** is the ripper: the heaviest body on the field and largely physical, with rot and infection riders that carry necrotic.
- **[[Kiro]]** is the venom-spewer, and the reason this encounter is the pit's real **Necrotic Resist** test. His venom kit deals its damage as necrotic rather than physical, so Physical Resist does nothing against him.

The tension is that Cade is the least threatening thing on the field to look at and the most threatening thing to leave alive. Leave him up and the beasts hit marked targets with escalating buffs; go for him first and you spend the opening turns eating beast damage undefended.

## What it teaches

Priority targeting against a support enemy, and the difference between the three damage types actually mattering. A build stacked entirely into Physical Resist will feel Kiro badly.

## Damage typing

Deliberately mixed: Oskar is mostly physical with necrotic riders, Kiro is heavily necrotic, Cade is physical. It is fine for an encounter to lean one way, but this one is built to cover ground.`,

  'elemental-duelists.md': `_Battle elite fire and ice duelists leveraging elemental reactions._

Two combatants, opposed elements, and the pit's only fight built on **cross-element interaction**. [[Ember]] and [[Rime]] are not two separate damage sources — they are one combined engine, and each half makes the other's payoff bigger.

## How the fight works

- **They build opposing meters on purpose.** Ember drives Fire buildup, Rime drives Cold. Neither is trying to reach a threshold alone; they are stacking *both* on you, because their kits pay out on the contrast between them.
- **Thermal Shock.** Once a target carries buildup in the opposing family, their cross-element abilities scale up. Letting both meters climb is strictly worse than letting either one climb alone.
- **Killing one enrages the other.** Both carry an on-ally-death rage: the survivor gains attack power, crit and Resilience, and unlocks an ability it could not previously cast. Dropping one duelist early does not halve the fight — it converts the remainder into something meaner.

That last point inverts the usual advice. Focusing one down is normally correct; here it hands the survivor a power spike. Either bring them down together, or be certain you can finish the second before the rage matters.

## What it teaches

Weakness meters are not a one-way accumulator you can ignore. This is the encounter where letting a meter fill is actively punished, and where Resilience — the only stat that actually reduces buildup accrual — earns its slot.

## Damage typing

Almost entirely elemental. Elemental Resist is the stat that matters here; Physical and Necrotic mitigation are close to dead weight.`,

  'gorrek.md': `_Gorrek — a relentless berserker who punishes hesitation and tears open his own wounds for power._

The pit's final fight, and a solo boss. Everything before this was about reading a formation; Gorrek is about reading **one** opponent who changes state as the fight goes on.

## How the fight works

- **He punishes standing still.** His glare is a free action that marks a target and demands they move by the end of their next turn — ignore it and it takes a substantial slice of maximum health. It costs him no action economy to threaten you with it.
- **His initiative builds fast**, and his self-buffs accelerate it further. Falling behind on the gauge compounds.
- **He feeds on his own wounds.** He carries lifesteal, and his healing scales up as his health falls — at the edge of death he recovers meaningfully more from every point of damage he deals. A slow grind at low health is exactly the wrong plan.
- **Death Spiral is gated.** It needs the target carrying **both** Expose and Lacerate at their second tier before he will commit to it. That gate is your warning: if you are letting both meters run, you are choosing to be hit by it.
- **He tears himself open deliberately.** Part of his kit applies Lacerate to *himself* in exchange for power, which is why leaving his bleeding unaddressed is a real decision rather than a free win.

## What it teaches

Action economy under pressure, and that weakness meters cut both ways. Gorrek is the exam for everything the pit has taught.

## The Reckoning

Beating him unlocks a rematch ladder. Each tier is account-wide and gates the next, and the design lever is **toughness first** — HP, resists and Resilience climb steadily while his damage stays deliberately restrained. His kit only grows at marked tiers, so the ladder is about your damage output holding up over a longer fight rather than about surviving new one-shots.

## Damage typing

Overwhelmingly physical. Physical Resist and Resilience are the defensive stats that pay here.`,
};

const ADVERSARY_PROSE = {
  'chad-the-unbreakable.md': `The wall of [[The Animated Six]], and the reason precision targeting fails against that formation.

Chad's defining trick is **redirection**: he can pull an incoming attack onto himself before the roll resolves, meaning a carefully aimed strike at a fragile back-rank construct simply lands on him instead, at his defences rather than theirs. He pairs that with self-buffs and a rallying call that hardens the whole group.

**Watch for:** committing your biggest single hit into what looks like an opening. If Chad is standing and healthy, assume he can take it for someone else.`,

  'shifty-eyed-mo.md': `The most annoying construct in the pit, and the one most people misread.

Mo is reactive: he answers the instant an ally is struck. The important detail is *when* his answer lands. His curse resolves **before your attack rolls**, so it weakens the very strike that triggered it — not the next one. Players who assume it is a normal debuff consistently under-account for it.

**Watch for:** your damage coming in lower than expected on the swing right after you hit one of his allies. That is Mo, not variance.`,

  'stan-of-the-light.md': `Genuine healing magic, running genuine healing logic.

Stan does not cast blindly. He filters to allies who are actually wounded, prefers the lowest-health target among them, and will not spend a cast on someone already at full health. His cleanse behaves the same way — it only fires on allies carrying real weakness buildup, never on an unafflicted target.

The practical consequence is that **spread chip damage is close to worthless** against his formation. Damage dealt evenly across six constructs is damage Stan can comfortably undo. Concentrated damage that threatens to actually kill something is what forces him to react.

**Watch for:** the moment he runs low on resources. He regenerates a small amount each turn, so a long fight favours him.`,

  'gary-the-grim.md': `The curse caster of [[The Animated Six]], and the pit's early source of necrotic pressure.

Gary works in layered affliction rather than raw output — curses, needles, and damage that bypasses physical mitigation entirely. He fights with the same tactical depth a real caster would, holding abilities for the moment they pay off rather than repeating one spell.

**Watch for:** stacking Physical Resist and assuming you are defended. Against Gary specifically, Necrotic Resist is the stat doing the work.`,

  'doug-longshot.md': `The ranged reactive of the formation.

Doug answers when an ally is struck, adding damage from the back rank. He is less individually dangerous than [[Shifty-Eyed Mo]] but contributes steadily, and being in the back rank means a fair number of melee approaches cannot reach him at all without repositioning first.

**Watch for:** treating the back rank as safe to ignore. Doug's contribution accumulates across a long fight.`,

  'lenny-the-magnificent.md': `The artillery of [[The Animated Six]].

Lenny channels a large area effect that has to be answered — left alone, it hits the whole party at once. He is fragile relative to his output, which makes him the classic focus-fire target, and precisely the target [[Chad the Unbreakable]] exists to protect.

**Watch for:** the channel. Once it starts, you are choosing between interrupting it and eating it.`,

  'cade.md': `The commander of [[Huntsman & Beasts]], and the encounter's real centre of gravity.

Cade deals comparatively little damage himself. What he does is **make his beasts' damage land**: marking targets to draw focus, applying Expose buildup, and handing the pack Initiative and Accuracy. His strongest pack buff is conditional — it only unlocks once a target already carries two or more active weaknesses — so his contribution escalates as the fight goes on and your meters fill.

**Watch for:** the temptation to fight the things that are hurting you. The beasts are the damage; Cade is the reason it connects.`,

  'oskar.md': `The ripper of [[Huntsman & Beasts]] — the heaviest body on that field.

Oskar is a brute: high health, physical output, and a straightforward threat profile compared to his packmate. What complicates him is rot. His infection and decay abilities carry a necrotic component, so he is not a pure physical problem even though he mostly reads as one.

**Watch for:** assuming the big melee beast is fully answered by Physical Resist. Part of his kit is not.`,

  'kiro.md': `The venom-spewer of [[Huntsman & Beasts]], and the pit's clearest **Necrotic Resist** test.

Kiro's kit is built on venom, and venom in this game is the Toxic family — whose own tier damage is necrotic. His abilities convert most or all of their damage to necrotic accordingly, from pure spat venom and gas clouds through to bites and swipes that carry a real physical component alongside the acid.

The practical consequence: a build stacked entirely into Physical Resist takes close to full damage from him. Necrotic Resist cuts it sharply.

**Watch for:** his reactive venom. It answers being hit and carries no physical component at all.`,

  'ember.md': `Half of the [[Elemental Duelists]], and the Fire side of their engine.

Ember drives Fire buildup, but the point is not Fire alone — it is the contrast with [[Rime]]'s Cold. Their cross-element payoffs scale on the target carrying buildup in the *opposing* family, so Ember's job is partly to make Rime's abilities hit harder.

If Rime dies first, Ember enrages: attack power, crit and Resilience all climb, and an ability unlocks that was previously unavailable.

**Watch for:** killing the other duelist and assuming the fight got easier.`,

  'rime.md': `Half of the [[Elemental Duelists]], and the Cold side of their engine.

Rime drives Cold buildup and carries Cold's own punishing side effects — reduced evasion and reduced outgoing damage on anyone whose meter climbs. Paired with [[Ember]]'s Fire, the two of them are stacking opposed meters on you specifically because their kits pay out on the contrast.

If Ember dies first, Rime enrages on the same terms: a real power spike, plus a newly unlocked ability.

**Watch for:** letting Cold climb quietly. Its penalties are not damage, so they are easy to miss until your accuracy and output have both quietly degraded.`,

  'gorrek-adversary.md': `The berserker at the end of the pit. See [[Gorrek]] for the full encounter, including the Reckoning ladder.

Gorrek's profile is deliberately lopsided: enormous health, heavy physical resistance and Resilience, and a damage output held on a tight leash by design. He is built to be a long fight rather than a lethal one — the danger is attrition and his own escalating recovery, not burst.

Three things define him mechanically:

- **Desperation healing.** All healing he receives, lifesteal included, scales up as his health falls — up to half again at the brink. Grinding him down slowly is the worst available plan.
- **Free action pressure.** His glare costs him nothing and threatens a large slice of your maximum health if you do not move.
- **Self-inflicted Lacerate.** Parts of his kit wound him deliberately in exchange for power, so his own bleeding is a resource he is spending rather than a problem you have given him.

**Watch for:** letting both Expose and Lacerate reach their second tier on one of your characters. That is the gate on Death Spiral, and it is the single largest hit in his kit.`,
};

let n = 0;
function seed(rel, prose, titleFromFile) {
  const full = join(OUT_DIR, rel);
  if (!existsSync(full)) { console.warn('  missing, skipped: ' + rel); return; }
  const cur = readFileSync(full, 'utf8');
  const i = cur.indexOf(GEN_START);
  if (i < 0) { console.warn('  no GEN marker, skipped: ' + rel); return; }
  // keep frontmatter + the "# Title" line, replace the prose between them
  const m = cur.match(/^---[\s\S]*?---\r?\n/);
  const fm = m ? m[0] : '';
  const rest = cur.slice(fm.length, i);
  const heading = (rest.match(/^#\s+.*$/m) || ['# ' + titleFromFile])[0];
  writeFileSync(full, fm + heading + NL + NL + prose + NL + NL + cur.slice(i), 'utf8');
  n++;
}

Object.keys(PROSE).forEach(k => seed(k, PROSE[k], k.replace('.md', '')));
Object.keys(ADVERSARY_PROSE).forEach(k => seed('adversaries/' + k, ADVERSARY_PROSE[k], k.replace('.md', '')));
console.log('seeded prose into ' + n + ' entries');
